Instructions to install rancher-prime payg on aws
SUSE-Enceladus/marketplace-docs pull request #29
Opened 2023-10-17 17:47 UTC by chajain

2023-10-17 17:55 UTC, mbelur requested changes
Overall looks good. I think we need to add a --timeout option to all the helm install/helm upgrade commands.

2023-10-17 19:09 UTC, guangyee approved these changes
lets do this

2023-10-17 22:08 UTC, jeremy-moffitt requested changes
Some very minor tweaks

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +   [Rancher support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/)
is there an unversioned version of this url? or do we have to update the docs for each release?

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +default                             external-dns                  1/1     1            1           9h
based on the conversation for the Azure docs, remove the external-dns item from this list

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +If any of the pods is not Running :
s/is/are/

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +if a pod is not in Running state, you can dig into the root cause by running:
s/dig/debug/

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +###ReRunning the installation because of customer Error
I'd probably add a dash to make it Re-running rather than ReRunning... could go either way

2023-10-17 22:08 UTC, jeremy-moffitt commented on content/rancher-prime/aws/contents.lr
> +if a configuration is not listed, you can dig into the root cause by checking the pod status and log (Refer Jobs and Pods section).
s/dig/debug/

2023-10-18 17:25 UTC, mbelur requested changes

2023-10-18 17:25 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +
we can add a step to monitor the rancher-cloud logs?

2023-10-18 17:25 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +
Should we add a note here that says that we use self-signed certificate for rancher installs?

2023-10-18 17:25 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +kube-system                         extension-agent               1/1     1            1           8h
looks like azure specific output..please update the output from the aws specific install. This is what I have for aws:
```NAMESPACE                           NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
cattle-csp-billing-adapter-system   csp-rancher-usage-operator    1/1     1            1           30m
cattle-csp-billing-adapter-system   rancher-csp-billing-adapter   1/1     1            1           30m
cattle-fleet-local-system           fleet-agent                   1/1     1            1           29m
cattle-fleet-system                 fleet-controller              1/1     1            1           29m
cattle-fleet-system                 gitjob                        1/1     1            1           29m
cattle-provisioning-capi-system     capi-controller-manager       1/1     1            1           28m
cattle-system                       rancher                       1/1     1            1           32m
cattle-system                       rancher-webhook               1/1     1            1           29m
cert-manager                        cert-manager                  1/1     1            1           32m
cert-manager                        cert-manager-cainjector       1/1     1            1           32m
cert-manager                        cert-manager-webhook          1/1     1            1           32m
ingress-nginx                       ingress-nginx-controller      1/1     1            1           33m
kube-system                         coredns                       2/2     2            2           38m
```

2023-10-18 20:59 UTC, mbelur requested changes

2023-10-18 20:59 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +base_product: cpe:/o:suse:rancher:v2.7.7
v2.7.8 to reflect current offer

2023-10-18 20:59 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +If the rancher-cloud pod is in Error state, wait for the pod to be deleted which takes approx 10 mins after it goes in Error State.
This is now 1 min..

2023-10-18 21:44 UTC, jeremy-moffitt approved these changes
The issues I raised have been resolved. Once Meera has confirmed her concerns have been addressed we should go ahead and merge this

2023-10-18 22:11 UTC, mbelur commented on content/rancher-prime/aws/contents.lr
> +###Re-Running the installation because of customer Error
This section seems to be duplicate of the previous section...

2023-10-18 22:44 UTC, mbelur approved these changes

2023-10-19 16:39 UTC, merged